name: Deploy to Development Cluster

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        python -m venv flask-local-test
        source flask-local-test/bin/activate
        pip install -r requirements.txt

    - name: Unit Test
      run: |
        source flask-local-test/bin/activate
        pytest test.py
        pytest test.py --html=report.html
        coverage run -m pytest test.py
        coverage report -m

    - name: Upload report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: report
        path: report.html

  pages:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download report artifact
        uses: actions/download-artifact@v3
        with:
          name: report

      - name: Setup Pages
        uses: actions/configure-pages@v5.0.0

      - name: Download report artifact
        uses: actions/download-artifact@v4
        with:
          name: report
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4.0.5

      - name: Build Docker Image and Push to DockerHub
        run: |
          SHA=$(git rev-parse --short HEAD)
          docker build -t maheshkumardash/flask-app:$SHA .
          docker login --username=${{ secrets.DOCKERUSERNAME }} --password=${{ secrets.DOCKERPASSWORD }}
          docker push maheshkumardash/flask-app:$SHA
